---
title: "README"
author: "Valeria Escrich"
format: gfm
---
## Data

This project uses St. Lawrence University Peer Tutoring Program appointment data. The dataset includes information on tutor and student IDs, course subjects, appointment times, class year, location, and form completition time. 

The data was cleaned and structures by grouping courses into broader subject areas, making student and tutor names anonymous, and modifying class years. Some variables,such as location, were expluded from the analysis due to lack of reliable variables.

## Questions

This project explores peer tutoring program functions from both tutors and student perspectives:

-   Is tutoring workload evenly distributed across tutors?
-   Do a small number of tutors handle most appointments?
-   Do students return to the same tutor over time?
-   When are tutoring appointments most likely to occur?
-   How do student characteristics, such as class year, influence tutoring usage?

## Graph

```{r}
#| echo: false


library(tidyverse)
library(readxl)
library(lubridate)
library(plotly)

tutoring = read_excel("data/MAIN_DATA.xlsx")
head(tutoring)

tutoring = tutoring |>
  mutate(
    start_time = parse_date_time(`Appointment Start Time`, orders = "I:M p"),
    end_time = parse_date_time(`Appointment End Time`, orders= "I:M p"),
    appointment_minutes = as.numeric(end_time - start_time, units = "mins"),
    start_hour = hour(start_time)
  )

scarlet = "#8B1E1E"
brown = "#4B2E1E"

top_tutors = tutoring |>
  group_by(`Tutor Id`)|>
  summarise(total_appointments = n()) |>
  arrange(desc(total_appointments)) |>
  slice(1:10)

tutoring = tutoring |>
  mutate(
    course_combined = if_else(is.na(COURSE), Class, COURSE)) |>
  mutate(
    course_group = case_when(
      is.na(course_combined)~"Missing",
      str_detect(course_combined, "STAT|Stat|stat") ~ "Statistics",
      str_detect(course_combined, "CHEM|Chem|chem") ~ "Chemistry",
      str_detect(course_combined, "BIO|Bio|bio") ~ "Biology",
      str_detect(course_combined,"ECON|Econ|econ|Financial Accounting|ACC 203 Financial Accounting") ~ "Economics",
      str_detect(course_combined,"PSYC|Psyc|psyc") ~ "Psychology",
      str_detect(course_combined,"PHYS|Phys|phys") ~ "Physics",
      str_detect(course_combined,"MATH|Math|math|Calculus 1|Calculus 2|Multivariable Calculus")~ "Mathematics",
      str_detect(course_combined,"CS|Computer|cs") ~ "Computer Science",
      str_detect(course_combined,"SPAN|Spanish|spanish")  ~ "Spanish",
      str_detect(course_combined,"SSES|Environment|General Ecology")  ~ "Environmental Sciences",
      str_detect(course_combined,"PHIL|philosophy")  ~ "Philosophy",
      str_detect(course_combined,"GER|German") ~ "German",
      str_detect(course_combined,"FREN|French|FR") ~ "French",
      str_detect(course_combined,"GOVT")  ~ "Government",
      TRUE~"Other"
    )
  )

tutoring |>
  filter(course_group == "Other") |>
  group_by(if_else(is.na(COURSE), Class, COURSE))|>
  summarise(total = n())|>
  arrange(desc(total))|>
  slice(1:30)

# Remove "Missing- 1101" which are students that didnt add anything 
tutor_specialization = tutoring |>
  filter(course_group != "Missing",
         course_group != "Other",
         `Tutor Id` %in% top_tutors$`Tutor Id`)|>
  group_by(`Tutor Id`, course_group) |>
  summarise(total = n(), .groups = "drop") |>
  ungroup()

tutor_order = top_tutors|>
  pull(`Tutor Id`)

course_order = tutor_specialization|>
  group_by(course_group)|>
  summarise(total_subject = sum(total))|>
  arrange(desc(total_subject))|>
  pull(course_group)

tutor_specialization = tutor_specialization |>
  mutate(
    `Tutor Id` = factor(`Tutor Id`, levels = tutor_order),
    course_group=factor(course_group, levels = course_order)
  )

figure3 = ggplot(tutor_specialization,
       aes(x=`Tutor Id`, y= course_group, fill = total,
           text = paste("Tutor: ", `Tutor Id`,
                        "Subject: ", course_group,
                        "Appointments: ", total)))+
  geom_tile( color = "white", linewidth = 0.4)+ 
  scale_fill_viridis_c()+
  labs(
    title = "Figure 3. Tutor Specialization Across Subject Areas",
    x = "Tutor Id",
    y = "Course Group",
    fill = "Appointments"
  )+
  theme_minimal()

ggplotly(figure3, tooltip = "text")
```

